name: Continuous integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@master
        with:
          ruby-version: 2.6.5

      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install libpq-dev

      - name: Cache Ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Bundle gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config set without 'production development'
          bundle install --jobs 4 --retry 3

      - name: Audit gems
        run: bundle exec bundle-audit check --update

      - name: Lint with RuboCop
        run: bundle exec rubocop --parallel

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node modules
        run: yarn install

      - name: Compile assets
        env:
          RAILS_ENV: test
          NODE_ENV: test
        run: bundle exec rails assets:precompile

      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_USER: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake db:create
          bundle exec rake test test:system
